build:
    environment:
        docker:
            remote_engine: true

    nodes:
        tests:
            dependencies:
                override:
                    - echo do nothing here
                before:
                    - echo do nothing here

    tests:
        override:
            - command: tests/run.sh unit
              idle_timeout: 500
              coverage:
                  file: coverage.xml
                  format: clover

